### ISSUE TITLE
Broken collapse panels on multiple pages

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2022.code4lib.org#59]
While working on opening keynote voting, I noticed there is an issue happening with keynote-nominees.html. The data is populated, but clicking the speaker names doesn't open the cards. I can see this may have been an issue on previous sites as well (links below).

I think this is also going to be an issue for other pages if we populate them, including proposed-talks, proposed-workshops, and proposed-posters.

We may also want to discuss if we want to continue maintaining these pages, which has come up in past years.

Example links:

Last year's nominees page (same issue): https://2021.code4lib.org/keynote/keynote-nominees.html
2020 Proposed talks page: https://2020.code4lib.org/talks/proposed-talks.html
2020 Proposed workshops page: https://2020.code4lib.org/workshops/proposed-workshops.html

**Comment by phette23** [comment]
I vote we not add this information to the site and clean it up by removing the related HTML files and example data.

Does anyone use the site for this info? The fact that voting happens elsewhere makes it not so useful. I'm sure most people don't even know it's here. We could spend more time focusing on other issues instead of syncing data, which can consume a lot of time.

In terms of fixing the feature, I don't think it would be hard. We need to add ARIA expanded/collapsed state, then JS to toggle the `card-collapse` elements and update that state and the classes on them. So it's not that it would be a hard fix but mostly that I don't think it's a good use of time to add proposed workshops, talks, and keynotes.

**Comment by kaitlinnewson** [comment]
I think the main reason we've kept it in the past has been for "archival" purposes. Is this data available anywhere else after the voting closes? But maybe there isn't value in having the past proposals, just the final program.

**Comment by phette23** [comment]
I don't think the proposals are listed elsewhere, except in closed voting forms where you can't read them. I think just having the final program available is all we need but I'm open to other opinions.

**Comment by dzoladz** [comment]
I've worked with a handful of state-level organizations in Ohio on both conference planning and website committees. I don't ever recall any of those orgs archiving proposals as part of the historical record. Is that a common practice elsewhere?

**Comment by phette23** [comment]
It's not a practice I'm aware of and I can't recall it coming up as an issue ever.

**Comment by dzoladz** [comment]
Removing `/posters/proposed-posters.html` as part of #138

**Comment by dzoladz** [comment]
As far as removal and cleanup to resolve this issue, we're talking about clearing out the code related to several other 'proposal vote' blocks, such as:
```
more-info-link='/general-info/propose-a-workshop.html'
more-info-text='About workshop proposals'
```

Right?

**Comment by phette23** [comment]
I think we want to retain pages that talk about what making a proposal entails but remove the list of proposals. So if that page under general-info is what I think it is, info on making a proposal, we'd keep it, but we'd drop workshops/proposed-workshops.html, talks/proposed-talks.html, and posters/proposed-posters.html as well as any example data we have for those pages.

**Comment by dzoladz** [comment]
Opened PR #157 to address this one. Another commit could be added to address the removal of any unneeded JS.
